import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [users, setUsers] = useState([]);

  const postsUrl = "https://jsonplaceholder.typicode.com/posts";
  const usersUrl = "https://jsonplaceholder.typicode.com/users";

  const fetchFromApi = async (url) => {
    // try {

    // } catch (error) {

    // }
    const response = await fetch(url);
    const jsonData = await response.json();

    if (url === postsUrl) {
      setPosts(jsonData);
    } else if (url === usersUrl) {
      setUsers(jsonData);
    }
  };

  useEffect(() => {
    fetchFromApi(postsUrl);
    fetchFromApi(usersUrl);
  }, []);

  console.log({ posts, users });

  return (
    <>
      <Head>
        <title>Integral - UI Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <table className="table-auto">
          <thead>
            <tr className="text-left">
              <th>Title</th>
              <th>Body</th>
              <th>Name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            {posts.map((post) => {
              const { title, body, id, userId } = post;
              return (
                <tr key={id}>
                  <td>{title}</td>
                  <td>{body}</td>
                  <td>{users.filter((user) => user.id === userId).name}</td>
                  <td>{users.filter((user) => user.id === userId).email}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>
    </>
  );
}
